{{- if and .Values.gatewayAPI.enabled .Values.gatewayAPI.ddash.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "ddash.fullname" . }}-ddash
spec:
  parentRefs:
{{ toYaml .Values.gatewayAPI.ddash.parentRefs | indent 4 }}
  hostnames:
{{ toYaml .Values.gatewayAPI.ddash.hostnames | indent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.gatewayAPI.ddash.pathPrefix | quote }}
      backendRefs:
        - name: {{ include "ddash.fullname" . }}-ddash
          port: {{ .Values.ddash.service.port }}
{{- end }}
{{- if and .Values.gatewayAPI.enabled .Values.githubIngestor.enabled .Values.gatewayAPI.githubIngestor.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "ddash.fullname" . }}-githubingestor
spec:
  parentRefs:
{{ toYaml .Values.gatewayAPI.githubIngestor.parentRefs | indent 4 }}
  hostnames:
{{ toYaml .Values.gatewayAPI.githubIngestor.hostnames | indent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.gatewayAPI.githubIngestor.pathPrefix | quote }}
      backendRefs:
        - name: {{ include "ddash.fullname" . }}-githubingestor
          port: {{ .Values.githubIngestor.service.port }}
{{- end }}
