apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ddash.fullname" . }}-secrets
type: Opaque
stringData:
  DDASH_SESSION_SECRET: {{ .Values.secrets.ddashSessionSecret | quote }}
  GITHUB_APP_INGESTOR_SETUP_TOKEN: {{ .Values.secrets.githubIngestorSetupToken | quote }}
  GITHUB_WEBHOOK_SECRET: {{ .Values.secrets.githubWebhookSecret | quote }}
