apiVersion: v1
kind: Secret
metadata:
  name: ddash-secrets
  namespace: ddash
type: Opaque
stringData:
  DDASH_SESSION_SECRET: change-me-long-random-secret
  GITHUB_APP_INGESTOR_SETUP_TOKEN: change-me-setup-token
  GITHUB_WEBHOOK_SECRET: change-me-github-webhook-secret
